export const Permission = {
  DashboardRead: "dashboard.read",
  LeadsRead: "leads.read",
  LeadsWrite: "leads.write",
  LeadsDelete: "leads.delete",
  LeadsImport: "leads.import",
  OutreachGenerate: "outreach.generate",
  MembersRead: "members.read",
  CustomersRead: "customers.read",
  CustomersWrite: "customers.write",
  ProjectsRead: "projects.read",
  ProjectsWrite: "projects.write",
  ProjectLineItemsRead: "project_line_items.read",
  ProjectLineItemsWrite: "project_line_items.write",
  LineItemTemplatesRead: "line_item_templates.read",
  LineItemTemplatesWrite: "line_item_templates.write",
  QuestionnaireTemplatesRead: "questionnaire_templates.read",
  QuestionnaireTemplatesWrite: "questionnaire_templates.write",
  TasksRead: "tasks.read",
  TasksWrite: "tasks.write",
  ChatRead: "chat.read",
  ChatWrite: "chat.write",
  ChatRedact: "chat.redact",
  FilesRead: "files.read",
  FilesWrite: "files.write",
  FilesDelete: "files.delete",
  CredentialsRead: "credentials.read",
  CredentialsReveal: "credentials.reveal",
  CredentialsWrite: "credentials.write",
  PortalAccessManage: "portal.manage",
  PortalAccess: "portal.access",
  PortalProjectsRead: "portal.projects.read",
  PortalTasksRead: "portal.tasks.read",
  PortalTasksComplete: "portal.tasks.complete",
  PortalTasksReopen: "portal.tasks.reopen",
  PortalTasksCreate: "portal.tasks.create",
  PortalMessagesRead: "portal.messages.read",
  PortalMessagesWrite: "portal.messages.write",
  PortalFilesRead: "portal.files.read",
  PortalFilesWrite: "portal.files.write",
  PortalFeedbackRead: "portal.feedback.read",
  PortalFeedbackSubmit: "portal.feedback.submit",
  PortalOnboardingRead: "portal.onboarding.read",
  PortalOnboardingSubmit: "portal.onboarding.submit",
  PortalCredentialsRead: "portal.credentials.read",
  PortalCredentialsReveal: "portal.credentials.reveal",
  PortalCredentialsWrite: "portal.credentials.write",
  RolesManage: "roles.manage",
  MembersManage: "members.manage",
  DataExport: "data.export",
  DataPurge: "data.purge",
  SecurityAudit: "security.audit",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

export const PERMISSION_VALUES = [
  Permission.DashboardRead,
  Permission.LeadsRead,
  Permission.LeadsWrite,
  Permission.LeadsDelete,
  Permission.LeadsImport,
  Permission.OutreachGenerate,
  Permission.MembersRead,
  Permission.CustomersRead,
  Permission.CustomersWrite,
  Permission.ProjectsRead,
  Permission.ProjectsWrite,
  Permission.ProjectLineItemsRead,
  Permission.ProjectLineItemsWrite,
  Permission.LineItemTemplatesRead,
  Permission.LineItemTemplatesWrite,
  Permission.QuestionnaireTemplatesRead,
  Permission.QuestionnaireTemplatesWrite,
  Permission.TasksRead,
  Permission.TasksWrite,
  Permission.ChatRead,
  Permission.ChatWrite,
  Permission.ChatRedact,
  Permission.FilesRead,
  Permission.FilesWrite,
  Permission.FilesDelete,
  Permission.CredentialsRead,
  Permission.CredentialsReveal,
  Permission.CredentialsWrite,
  Permission.PortalAccessManage,
  Permission.PortalAccess,
  Permission.PortalProjectsRead,
  Permission.PortalTasksRead,
  Permission.PortalTasksComplete,
  Permission.PortalTasksReopen,
  Permission.PortalTasksCreate,
  Permission.PortalMessagesRead,
  Permission.PortalMessagesWrite,
  Permission.PortalFilesRead,
  Permission.PortalFilesWrite,
  Permission.PortalFeedbackRead,
  Permission.PortalFeedbackSubmit,
  Permission.PortalOnboardingRead,
  Permission.PortalOnboardingSubmit,
  Permission.PortalCredentialsRead,
  Permission.PortalCredentialsReveal,
  Permission.PortalCredentialsWrite,
  Permission.RolesManage,
  Permission.MembersManage,
  Permission.DataExport,
  Permission.DataPurge,
  Permission.SecurityAudit,
] as const;
