export const Permission = {
  DashboardRead: "dashboard.read",
  LeadsRead: "leads.read",
  LeadsWrite: "leads.write",
  LeadsDelete: "leads.delete",
  LeadsImport: "leads.import",
  OutreachGenerate: "outreach.generate",
  MembersRead: "members.read",
  CustomersRead: "customers.read",
  CustomersWrite: "customers.write",
  ProjectsRead: "projects.read",
  ProjectsWrite: "projects.write",
  ProjectLineItemsRead: "project_line_items.read",
  ProjectLineItemsWrite: "project_line_items.write",
  LineItemTemplatesRead: "line_item_templates.read",
  LineItemTemplatesWrite: "line_item_templates.write",
  TasksRead: "tasks.read",
  TasksWrite: "tasks.write",
  FilesRead: "files.read",
  FilesWrite: "files.write",
  FilesDelete: "files.delete",
  CredentialsRead: "credentials.read",
  CredentialsReveal: "credentials.reveal",
  CredentialsWrite: "credentials.write",
  PortalAccessManage: "portal.manage",
  PortalAccess: "portal.access",
  RolesManage: "roles.manage",
  MembersManage: "members.manage",
  DataExport: "data.export",
  DataPurge: "data.purge",
  SecurityAudit: "security.audit",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

export const PERMISSION_VALUES = [
  Permission.DashboardRead,
  Permission.LeadsRead,
  Permission.LeadsWrite,
  Permission.LeadsDelete,
  Permission.LeadsImport,
  Permission.OutreachGenerate,
  Permission.MembersRead,
  Permission.CustomersRead,
  Permission.CustomersWrite,
  Permission.ProjectsRead,
  Permission.ProjectsWrite,
  Permission.ProjectLineItemsRead,
  Permission.ProjectLineItemsWrite,
  Permission.LineItemTemplatesRead,
  Permission.LineItemTemplatesWrite,
  Permission.TasksRead,
  Permission.TasksWrite,
  Permission.FilesRead,
  Permission.FilesWrite,
  Permission.FilesDelete,
  Permission.CredentialsRead,
  Permission.CredentialsReveal,
  Permission.CredentialsWrite,
  Permission.PortalAccessManage,
  Permission.PortalAccess,
  Permission.RolesManage,
  Permission.MembersManage,
  Permission.DataExport,
  Permission.DataPurge,
  Permission.SecurityAudit,
] as const;
