import type { FeedbackItemKind } from "../../constants/crm/feedback-item-kinds";

/** One item of a draft save; the position is its index in the list. */
export interface PortalFeedbackDraftItemDto {
  /** Generated by the client and kept across autosaves; an unknown id creates the item. */
  id: string;
  /** One of the round's `areaOptions`; null means "general". */
  areaLabel: string | null;
  /** Optional classification; null when left open. */
  kind: FeedbackItemKind | null;
  /** Raw plain text, stored as typed; may be empty until the round is submitted. */
  body: string;
}
