/** Stable operation names for CRM route logs; never contain ids, names or emails. */
export const CrmOperation = {
  ConvertLead: "leads.convert",
  ListCustomers: "customers.list",
  CreateCustomer: "customers.create",
  GetCustomer: "customers.get",
  UpdateCustomer: "customers.update",
  ListProjectLineItems: "project-line-items.list",
  CreateProjectLineItem: "project-line-items.create",
  UpdateProjectLineItem: "project-line-items.update",
  ListLineItemTemplates: "line-item-templates.list",
  CreateLineItemTemplate: "line-item-templates.create",
  UpdateLineItemTemplate: "line-item-templates.update",
  ListQuestionnaireBlocks: "questionnaire-blocks.list",
  GetQuestionnaireBlock: "questionnaire-blocks.get",
  CreateQuestionnaireBlock: "questionnaire-blocks.create",
  UpdateQuestionnaireBlock: "questionnaire-blocks.update",
  DeleteQuestionnaireBlock: "questionnaire-blocks.delete",
  DuplicateQuestionnaireBlock: "questionnaire-blocks.duplicate",
  CreateQuestionnaireField: "questionnaire-fields.create",
  UpdateQuestionnaireField: "questionnaire-fields.update",
  DeleteQuestionnaireField: "questionnaire-fields.delete",
  MoveQuestionnaireField: "questionnaire-fields.move",
  ListQuestionnaireTemplates: "questionnaire-templates.list",
  GetQuestionnaireTemplate: "questionnaire-templates.get",
  CreateQuestionnaireTemplate: "questionnaire-templates.create",
  UpdateQuestionnaireTemplate: "questionnaire-templates.update",
  ListTasks: "tasks.list",
  CreateTask: "tasks.create",
  UpdateTask: "tasks.update",
  ChangeTaskStatus: "tasks.change-status",
  GetConversation: "conversations.get",
  CountUnreadConversations: "conversations.count-unread",
  MarkConversationRead: "conversations.mark-read",
  UpdateConversationOwner: "conversations.update-owner",
  SendMessage: "messages.send",
  RedactMessage: "messages.redact",
  GetPortalConversation: "portal-conversations.get",
  MarkPortalConversationRead: "portal-conversations.mark-read",
  SendPortalMessage: "portal-messages.send",
  ListFeedbackRounds: "feedback-rounds.list",
  HandOverFeedbackRound: "feedback-rounds.hand-over",
  GetFeedbackRound: "feedback-rounds.get",
  ChangeFeedbackRoundStatus: "feedback-rounds.change-status",
  SetFeedbackItemResult: "feedback-items.set-result",
  ListFeedbackInbox: "feedback-rounds.list-inbox",
  CountUnreadFeedbackRounds: "feedback-rounds.count-unread",
  MarkFeedbackRoundRead: "feedback-rounds.mark-read",
  GetProjectOnboarding: "onboarding-forms.get-for-project",
  StartProjectOnboarding: "onboarding-forms.start",
  GetOnboardingForm: "onboarding-forms.get",
  AddOnboardingFormBlock: "onboarding-form-blocks.add",
  UpdateOnboardingFormBlock: "onboarding-form-blocks.update",
  RemoveOnboardingFormBlock: "onboarding-form-blocks.remove",
  MoveOnboardingFormBlock: "onboarding-form-blocks.move",
  CreateOnboardingFormField: "onboarding-form-fields.create",
  UpdateOnboardingFormField: "onboarding-form-fields.update",
  DeleteOnboardingFormField: "onboarding-form-fields.delete",
  MoveOnboardingFormField: "onboarding-form-fields.move",
  GetOnboardingFieldUsage: "onboarding-form-fields.usage",
  ReleaseOnboardingForm: "onboarding-forms.release",
  ReviewOnboardingBlock: "onboarding-form-blocks.review",
  RequestOnboardingChanges: "onboarding-forms.request-changes",
} as const;

export type CrmOperation = (typeof CrmOperation)[keyof typeof CrmOperation];

export const CRM_OPERATION_VALUES = [
  CrmOperation.ConvertLead,
  CrmOperation.ListCustomers,
  CrmOperation.CreateCustomer,
  CrmOperation.GetCustomer,
  CrmOperation.UpdateCustomer,
  CrmOperation.ListProjectLineItems,
  CrmOperation.CreateProjectLineItem,
  CrmOperation.UpdateProjectLineItem,
  CrmOperation.ListLineItemTemplates,
  CrmOperation.CreateLineItemTemplate,
  CrmOperation.UpdateLineItemTemplate,
  CrmOperation.ListQuestionnaireBlocks,
  CrmOperation.GetQuestionnaireBlock,
  CrmOperation.CreateQuestionnaireBlock,
  CrmOperation.UpdateQuestionnaireBlock,
  CrmOperation.DeleteQuestionnaireBlock,
  CrmOperation.DuplicateQuestionnaireBlock,
  CrmOperation.CreateQuestionnaireField,
  CrmOperation.UpdateQuestionnaireField,
  CrmOperation.DeleteQuestionnaireField,
  CrmOperation.MoveQuestionnaireField,
  CrmOperation.ListQuestionnaireTemplates,
  CrmOperation.GetQuestionnaireTemplate,
  CrmOperation.CreateQuestionnaireTemplate,
  CrmOperation.UpdateQuestionnaireTemplate,
  CrmOperation.ListTasks,
  CrmOperation.CreateTask,
  CrmOperation.UpdateTask,
  CrmOperation.ChangeTaskStatus,
  CrmOperation.GetConversation,
  CrmOperation.CountUnreadConversations,
  CrmOperation.MarkConversationRead,
  CrmOperation.UpdateConversationOwner,
  CrmOperation.SendMessage,
  CrmOperation.RedactMessage,
  CrmOperation.GetPortalConversation,
  CrmOperation.MarkPortalConversationRead,
  CrmOperation.SendPortalMessage,
  CrmOperation.ListFeedbackRounds,
  CrmOperation.HandOverFeedbackRound,
  CrmOperation.GetFeedbackRound,
  CrmOperation.ChangeFeedbackRoundStatus,
  CrmOperation.SetFeedbackItemResult,
  CrmOperation.ListFeedbackInbox,
  CrmOperation.CountUnreadFeedbackRounds,
  CrmOperation.MarkFeedbackRoundRead,
  CrmOperation.GetProjectOnboarding,
  CrmOperation.StartProjectOnboarding,
  CrmOperation.GetOnboardingForm,
  CrmOperation.AddOnboardingFormBlock,
  CrmOperation.UpdateOnboardingFormBlock,
  CrmOperation.RemoveOnboardingFormBlock,
  CrmOperation.MoveOnboardingFormBlock,
  CrmOperation.CreateOnboardingFormField,
  CrmOperation.UpdateOnboardingFormField,
  CrmOperation.DeleteOnboardingFormField,
  CrmOperation.MoveOnboardingFormField,
  CrmOperation.GetOnboardingFieldUsage,
  CrmOperation.ReleaseOnboardingForm,
  CrmOperation.ReviewOnboardingBlock,
  CrmOperation.RequestOnboardingChanges,
] as const;
