/** Stable operation names for CRM route logs; never contain ids, names or emails. */
export const CrmOperation = {
  ConvertLead: "leads.convert",
  ListCustomers: "customers.list",
  CreateCustomer: "customers.create",
  GetCustomer: "customers.get",
  UpdateCustomer: "customers.update",
  ListProjectLineItems: "project-line-items.list",
  CreateProjectLineItem: "project-line-items.create",
  UpdateProjectLineItem: "project-line-items.update",
  ListLineItemTemplates: "line-item-templates.list",
  CreateLineItemTemplate: "line-item-templates.create",
  UpdateLineItemTemplate: "line-item-templates.update",
  ListTasks: "tasks.list",
  CreateTask: "tasks.create",
  UpdateTask: "tasks.update",
  ChangeTaskStatus: "tasks.change-status",
  GetConversation: "conversations.get",
  CountUnreadConversations: "conversations.count-unread",
  MarkConversationRead: "conversations.mark-read",
  UpdateConversationOwner: "conversations.update-owner",
  SendMessage: "messages.send",
  RedactMessage: "messages.redact",
  GetPortalConversation: "portal-conversations.get",
  MarkPortalConversationRead: "portal-conversations.mark-read",
  SendPortalMessage: "portal-messages.send",
  ListFeedbackRounds: "feedback-rounds.list",
  HandOverFeedbackRound: "feedback-rounds.hand-over",
  GetFeedbackRound: "feedback-rounds.get",
  ChangeFeedbackRoundStatus: "feedback-rounds.change-status",
  SetFeedbackItemResult: "feedback-items.set-result",
  ListFeedbackInbox: "feedback-rounds.list-inbox",
  CountUnreadFeedbackRounds: "feedback-rounds.count-unread",
  MarkFeedbackRoundRead: "feedback-rounds.mark-read",
} as const;

export type CrmOperation = (typeof CrmOperation)[keyof typeof CrmOperation];

export const CRM_OPERATION_VALUES = [
  CrmOperation.ConvertLead,
  CrmOperation.ListCustomers,
  CrmOperation.CreateCustomer,
  CrmOperation.GetCustomer,
  CrmOperation.UpdateCustomer,
  CrmOperation.ListProjectLineItems,
  CrmOperation.CreateProjectLineItem,
  CrmOperation.UpdateProjectLineItem,
  CrmOperation.ListLineItemTemplates,
  CrmOperation.CreateLineItemTemplate,
  CrmOperation.UpdateLineItemTemplate,
  CrmOperation.ListTasks,
  CrmOperation.CreateTask,
  CrmOperation.UpdateTask,
  CrmOperation.ChangeTaskStatus,
  CrmOperation.GetConversation,
  CrmOperation.CountUnreadConversations,
  CrmOperation.MarkConversationRead,
  CrmOperation.UpdateConversationOwner,
  CrmOperation.SendMessage,
  CrmOperation.RedactMessage,
  CrmOperation.GetPortalConversation,
  CrmOperation.MarkPortalConversationRead,
  CrmOperation.SendPortalMessage,
  CrmOperation.ListFeedbackRounds,
  CrmOperation.HandOverFeedbackRound,
  CrmOperation.GetFeedbackRound,
  CrmOperation.ChangeFeedbackRoundStatus,
  CrmOperation.SetFeedbackItemResult,
  CrmOperation.ListFeedbackInbox,
  CrmOperation.CountUnreadFeedbackRounds,
  CrmOperation.MarkFeedbackRoundRead,
] as const;
