export const FeedbackRoundsConstraintName = {
  ProjectCustomerForeignKey: "feedback_rounds_project_customer_fk",
  HandedOverByForeignKey: "feedback_rounds_handed_over_by_fk",
  DraftUpdatedByForeignKey: "feedback_rounds_draft_updated_by_fk",
  SubmittedByForeignKey: "feedback_rounds_submitted_by_fk",
  CompletedByForeignKey: "feedback_rounds_completed_by_fk",
  ApprovedByForeignKey: "feedback_rounds_approved_by_fk",
  IdProjectUnique: "feedback_rounds_id_project_uidx",
  ProjectNumberUnique: "feedback_rounds_project_number_uidx",
  RoundNumberCheck: "feedback_rounds_round_number_check",
  StatusCheck: "feedback_rounds_status_check",
  PreviewUrlCheck: "feedback_rounds_preview_url_check",
  HandoverNoteCheck: "feedback_rounds_handover_note_check",
  AreaOptionsCheck: "feedback_rounds_area_options_check",
  CustomerNoticeCheck: "feedback_rounds_customer_notice_check",
  VersionCheck: "feedback_rounds_version_check",
  OpenUnsubmittedCheck: "feedback_rounds_open_unsubmitted_check",
  SubmittedCheck: "feedback_rounds_submitted_check",
  SubmittedByCheck: "feedback_rounds_submitted_by_check",
  StartedCheck: "feedback_rounds_started_check",
  CompletedCheck: "feedback_rounds_completed_check",
  CompletedAtCheck: "feedback_rounds_completed_at_check",
  ApprovedCheck: "feedback_rounds_approved_check",
  ActiveUnique: "feedback_rounds_active_uidx",
  ApprovedUnique: "feedback_rounds_approved_uidx",
  QueueIndex: "feedback_rounds_queue_idx",
  UnreadIndex: "feedback_rounds_unread_idx",
} as const;
