export const FilesConstraintName = {
  CustomerForeignKey: "files_customer_fk",
  ProjectCustomerForeignKey: "files_project_customer_fk",
  MemberForeignKey: "files_member_fk",
  PortalMembershipForeignKey: "files_portal_membership_fk",
  StorageKeyUnique: "files_storage_key_unique",
  IdCustomerUnique: "files_id_customer_unique",
  SourceCheck: "files_source_check",
  StatusCheck: "files_status_check",
  AssetKindCheck: "files_asset_kind_check",
  DisplayNameCheck: "files_display_name_check",
  NoteCheck: "files_note_check",
  UploadSideCheck: "files_upload_side_check",
  SizeCheck: "files_size_check",
  InspectionCheck: "files_inspection_check",
  UrlCheck: "files_url_check",
  VersionCheck: "files_version_check",
  SourceFieldsCheck: "files_source_fields_check",
  UploaderCheck: "files_uploader_check",
  CustomerVisibleCheck: "files_customer_visible_check",
  CustomerReadyIndex: "files_customer_ready_idx",
  ProjectIndex: "files_project_idx",
  CustomerVisibleIndex: "files_customer_visible_idx",
  PendingIndex: "files_pending_idx",
} as const;
