export const OnboardingFieldsConstraintName = {
  BlockForeignKey: "onboarding_fields_block_fk",
  ParentForeignKey: "onboarding_fields_parent_fk",
  ConditionChoiceForeignKey: "onboarding_fields_condition_choice_fk",
  BlockKeyUnique: "onboarding_fields_block_key_uidx",
  PositionUnique: "onboarding_fields_position_uidx",
  KeyCheck: "onboarding_fields_key_check",
  PositionCheck: "onboarding_fields_position_check",
  TypeCheck: "onboarding_fields_type_check",
  RequirementCheck: "onboarding_fields_requirement_check",
  MaxLengthCheck: "onboarding_fields_max_length_check",
  MinItemsCheck: "onboarding_fields_min_items_check",
  MaxItemsCheck: "onboarding_fields_max_items_check",
  PrefillSourceCheck: "onboarding_fields_prefill_source_check",
  VersionCheck: "onboarding_fields_version_check",
  ConditionPairCheck: "onboarding_fields_condition_pair_check",
  ItemRangeCheck: "onboarding_fields_item_range_check",
  MaxLengthTypeCheck: "onboarding_fields_max_length_type_check",
  ItemCountTypeCheck: "onboarding_fields_item_count_type_check",
  AssetKindsTypeCheck: "onboarding_fields_asset_kinds_type_check",
  ParentTypeCheck: "onboarding_fields_parent_type_check",
  BlockIndex: "onboarding_fields_block_idx",
} as const;
