export const OnboardingFormsConstraintName = {
  ProjectCustomerForeignKey: "onboarding_forms_project_customer_fk",
  SourceTemplateForeignKey: "onboarding_forms_source_template_fk",
  CreatedByForeignKey: "onboarding_forms_created_by_fk",
  ReleasedByForeignKey: "onboarding_forms_released_by_fk",
  SubmittedByForeignKey: "onboarding_forms_submitted_by_fk",
  ServicesConfirmedByForeignKey: "onboarding_forms_services_confirmed_by_fk",
  CompletedByForeignKey: "onboarding_forms_completed_by_fk",
  ProjectUnique: "onboarding_forms_project_uidx",
  IdCustomerUnique: "onboarding_forms_id_customer_uidx",
  IdProjectUnique: "onboarding_forms_id_project_uidx",
  StatusCheck: "onboarding_forms_status_check",
  ServicesNoteCheck: "onboarding_forms_services_note_check",
  VersionCheck: "onboarding_forms_version_check",
  ReleasedCheck: "onboarding_forms_released_check",
  ReleasedByCheck: "onboarding_forms_released_by_check",
  SubmittedCheck: "onboarding_forms_submitted_check",
  CompletedCheck: "onboarding_forms_completed_check",
  ServicesConfirmedCheck: "onboarding_forms_services_confirmed_check",
  CustomerIndex: "onboarding_forms_customer_idx",
} as const;
