export const QuestionnaireFieldsConstraintName = {
  BlockForeignKey: "questionnaire_fields_block_fk",
  ParentForeignKey: "questionnaire_fields_parent_fk",
  ConditionChoiceForeignKey: "questionnaire_fields_condition_choice_fk",
  BlockKeyUnique: "questionnaire_fields_block_key_uidx",
  PositionUnique: "questionnaire_fields_position_uidx",
  KeyCheck: "questionnaire_fields_key_check",
  PositionCheck: "questionnaire_fields_position_check",
  TypeCheck: "questionnaire_fields_type_check",
  RequirementCheck: "questionnaire_fields_requirement_check",
  MaxLengthCheck: "questionnaire_fields_max_length_check",
  MinItemsCheck: "questionnaire_fields_min_items_check",
  MaxItemsCheck: "questionnaire_fields_max_items_check",
  PrefillSourceCheck: "questionnaire_fields_prefill_source_check",
  VersionCheck: "questionnaire_fields_version_check",
  ConditionPairCheck: "questionnaire_fields_condition_pair_check",
  ItemRangeCheck: "questionnaire_fields_item_range_check",
  MaxLengthTypeCheck: "questionnaire_fields_max_length_type_check",
  ItemCountTypeCheck: "questionnaire_fields_item_count_type_check",
  AssetKindsTypeCheck: "questionnaire_fields_asset_kinds_type_check",
  ParentTypeCheck: "questionnaire_fields_parent_type_check",
  BlockIndex: "questionnaire_fields_block_idx",
} as const;
